FLASK_DEBUG = True
FLASK_SERVER_URL = ""
FLASK_SERVER_URL_DEBUG = "localhost:8888"

RESTPLUS_SWAGGER_UI_DOC_EXPANSION = "list"
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

SQLALCHEMY_DATABASE_URI = ""
SQLALCHEMY_DATABASE_URI_DEBUG = "sqlite:///db.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = False
