MESSAGE = "message"

SERVER_NAME = "SERVER_NAME"
SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
SQLALCHEMY_TRACK_MODIFICATIONS = "SQLALCHEMY_TRACK_MODIFICATIONS"
SWAGGER_UI_DOC_EXPANSION = "SWAGGER_UI_DOC_EXPANSION"
RESTPLUS_VALIDATE = "RESTPLUS_VALIDATE"
RESTPLUS_MASK_SWAGGER = "RESTPLUS_MASK_SWAGGER"
ERROR_404_HELP = "ERROR_404_HELP"
